### ISSUE TITLE
Potential performance issue when enqueuing a large amount of operations

### ISSUE THREAD

**Issue by aurrak** [mattmassicotte/Queue#1]
There seems to be a bottleneck when adding a large amount of operations.

For example, running the following experiment on my machine, enqueuing about 1000 operations is just fine. However, if I increase the operations to a higher number to like 30_000, the code seems to wait for all the pendingTasks to be accumulated instead of trying to also run the already enqueued tasks concurrently? Also observe that the memory goes way up (to the amount of GBs) and seemingly takes a long time for the pending tasks to even start running.

Removing the `@MainActor` from the `experiment` function seems to help a tiny bit, but it's still significantly slower than some other serial queuing implementations that makes use of `AsyncStream`.

```swift
import Foundation

@main
struct Test {
    actor Counter {
        var count: Int = 0
        func increment() -> Int {
            count += 1
            print("Incremented: \(count)")
            return count
        }
    }

    @MainActor
    func experiment() {
        let queue = AsyncQueue()
        let s = Counter()
        for i in 1 ... 100_000 {
            queue.addOperation { [i] in
                let result = await s.increment()
                if i != result {
                    print(i, "does not match", result)
                }
            }
        }
    }

    static func main () async {
        print ("test starting")
        Test().experiment()
        print ("test started")
        try! await Task.sleep(for: .seconds(5))
        print ("test finished")
    }
}
```

**Comment by mattmassicotte** [comment]
I think that 818219f458ff51ebf7651f1d1617fa4e3694956c addresses this. The performance is now much better and peak memory usage seems to have a much more reasonable ceiling.

Still every interested in an `AsyncSequence`-based solution though!

**Comment by aurrak** [comment]
Thanks for looking into it! I verified that it's indeed way faster with [818219f](https://github.com/mattmassicotte/Queue/commit/818219f458ff51ebf7651f1d1617fa4e3694956c)

The other solution that's based on `AsyncStream` can be found [here](https://github.com/dfed/swift-async-queue). That solution doesn't use any lock and simply relies on the stream/continuation for thread-safe buffering. I think the `enqueueAndWait` method can be used as a barrier variant.

Some relevant discussion can be found in the [Swift forum](https://forums.swift.org/t/task-is-order-of-task-execution-deterministic/51553/39).

**Comment by mattmassicotte** [comment]
Great! Thanks again for reporting this, I really appreciate it. And also for the pointer to that other library. It looks really interesting - I'm going to put a link to it in the readme just in case.
