### ISSUE TITLE
Inconsistent repo name

### ISSUE THREAD

**Issue by mkeiser** [mattmassicotte/Queue#2]
Hey, thanks for this interesting repo!

A thing I noticed is that the readme mentions [here](https://github.com/mattmassicotte/Queue#integration) that to integrate you should add `.package(url: "https://github.com/mattmassicotte/AsyncQueue", from: "0.1.4")`, where in fact the package name is just `Queue`.
Imo, `AsyncQueue` would be a better name for it, but at least the readme should change to mentioned to correct name, whatever it is. :D

**Comment by mattmassicotte** [comment]
Ugh, what an awful mistake. Thank you so much for pointing it out! Fixed!

Also, I just wanted to explain. When you have a type with the same name as a module, Swift has no way to disambiguate the two. This isn't always an issue, but I have been bitten by it a few times. The only solution that exists today is to avoid giving the same name to a module and type within that module. So, I agree that "AsyncQueue" would be a better name, but there are real technical problems with it. The swift team is aware of this issue, but unfortunately a fix is non-trivial, and may never come 😕

**Comment by mkeiser** [comment]
> When you have a type with the same name as a module, Swift has no way to disambiguate the two

Ah, I had no idea.
